create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  thumbnail text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.prompts (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  thumbnail text,
  prompt_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists prompts_category_id_idx on public.prompts(category_id);

alter table public.categories enable row level security;
alter table public.prompts enable row level security;

-- This app currently has no sign-in screen, so public visitors can use the manager.
-- The frontend only exposes the publishable/anon key; these policies do not expose service-role credentials.
drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories" on public.categories for select using (true);
drop policy if exists "Public can add categories" on public.categories;
create policy "Public can add categories" on public.categories for insert with check (true);
drop policy if exists "Public can edit categories" on public.categories;
create policy "Public can edit categories" on public.categories for update using (true) with check (true);
drop policy if exists "Public can delete categories" on public.categories;
create policy "Public can delete categories" on public.categories for delete using (true);

drop policy if exists "Public can read prompts" on public.prompts;
create policy "Public can read prompts" on public.prompts for select using (true);
drop policy if exists "Public can add prompts" on public.prompts;
create policy "Public can add prompts" on public.prompts for insert with check (true);
drop policy if exists "Public can edit prompts" on public.prompts;
create policy "Public can edit prompts" on public.prompts for update using (true) with check (true);
drop policy if exists "Public can delete prompts" on public.prompts;
create policy "Public can delete prompts" on public.prompts for delete using (true);

insert into public.categories (id, name)
select * from (values
  (1::bigint, 'Jersey Mockup'),
  (2::bigint, 'Logo Mockup'),
  (3::bigint, 'Personal Photo')
) as seed(id, name)
where not exists (select 1 from public.categories);

select setval(pg_get_serial_sequence('public.categories', 'id'), greatest((select coalesce(max(id), 1) from public.categories), 1), true);

insert into storage.buckets (id, name, public)
values ('prompt-images', 'prompt-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read prompt images" on storage.objects;
create policy "Public can read prompt images" on storage.objects for select using (bucket_id = 'prompt-images');
drop policy if exists "Public can upload prompt images" on storage.objects;
create policy "Public can upload prompt images" on storage.objects for insert with check (bucket_id = 'prompt-images');
drop policy if exists "Public can update prompt images" on storage.objects;
create policy "Public can update prompt images" on storage.objects for update using (bucket_id = 'prompt-images') with check (bucket_id = 'prompt-images');
drop policy if exists "Public can delete prompt images" on storage.objects;
create policy "Public can delete prompt images" on storage.objects for delete using (bucket_id = 'prompt-images');
